const news = [
    {
        id:"1",
        type:"cccccccccc",
        img:"https://i.ibb.co/VqSRY1g/busi1.jpg",
        time:"07/4/2022  8:10 am",
        heading:"State Minister for Power, Energy and Mineral Resources, Nasrul Hamid, today said power generation is facing disruption due to a shortage in gas supply.",
        details:"Power generation will return to full normalcy once gas supply is restored, the state minister also said.Due to rise in price of fuel in international market as a consequence of the ongoing war between Ukraine and Russia, the country is facing a supply crunch of fuel like the rest of the world, he said.Power generation will return to full normalcy once gas supply is restored, the state minister also said.Due to rise in price of fuel in international market as a consequence of the ongoing war between Ukraine and Russia, the country is facing a supply crunch of fuel like the rest of the world, he said.Power generation will return to full normalcy once gas supply is restored, the state minister also said.Due to rise in price of fuel in international market as a consequence of the ongoing war between Ukraine and Russia, the country is facing a supply crunch of fuel like the rest of the world, he said."
    },
    {
        id:2,
        type:"bangladesh",
        img:"https://i.ibb.co/N2s1YSv/bd2.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Gas is being emitted from an enclosure at a fish farm in Mongla of Bagerhat. The landowner's family is now using the gas for cooking.",
        details:"Gas came out from here about five or six years ago too, but no one ever came to inspect. We can't say how much gas there is. The concerned authorities need to take steps quickly in this regard, otherwise, there could be major damage at any time.Mongla Upazila Nirbahi Officer (UNO) Kamlesh Majumder said.The gas began coming out on Thursday, June 30, 2022 morning during sand extraction from the enclosure, and has continued since then, spewing a mix of gas with sand and water.Gas came out from here about five or six years ago too, but no one ever came to inspect. We can't say how much gas there is. The concerned authorities need to take steps quickly in this regard, otherwise, there could be major damage at any time.Mongla Upazila Nirbahi Officer (UNO) Kamlesh Majumder said.The gas began coming out on Thursday, June 30, 2022 morning during sand extraction from the enclosure, and has continued since then, spewing a mix of gas with sand and water.  "
    },{
        id:3,
        type:"business",
        img:"https://i.ibb.co/F0GjfGD/b3.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Russia is increasing gasoline and naphtha supplies to Africa and the Middle East as it struggles to sell fuel in Europe, while Asia is already taking bigger volumes of Russian crude, Refinitiv Eikon data showed and sources said.",
        details:"The development is likely to increase competition for Asian customers between Russia and other big fuel exporters Saudi Arabia and the United States which are the top three suppliers to Asia.The European Union has slowly reduced imports of Russian crude and fuel since March and agreed a full embargo that will take effect by end-2022.Asian buyers have stepped in to rapidly increase purchases of Russian crude, even though Asia is not a natural market for Russian fuel because Asia refines more oil than it needs and is a net fuel exporter.The development is likely to increase competition for Asian customers between Russia and other big fuel exporters Saudi Arabia and the United States which are the top three suppliers to Asia.The European Union has slowly reduced imports of Russian crude and fuel since March and agreed a full embargo that will take effect by end-2022.Asian buyers have stepped in to rapidly increase purchases of Russian crude, even though Asia is not a natural market for Russian fuel because Asia refines more oil than it needs and is a net fuel exporter.That makes finding new outlets such as Africa and the Middle East paramount for Russia to protect its global market share and avert a deeper decline in oil exports and output."
    },{
        id:4,
        type:"business",
        img:"https://i.ibb.co/t4JR6tp/b4.jpg",
        time:"07/4/2022  8:10 am",
        heading:"The government today asked all the owners of factories and industries, including those in the garments sector, to pay the due salary and bonus to their workers by July 7, three days ahead of Eid-ul-Azha.",
        details:"Begum Monnuzan Sufian, state minister for labour and employment, came up with the directives after a tripartite meeting of garment factory owners, union leaders and government officials at Sromo Bhaban in Dhaka.Sufian also said the workers' Eid holiday will be aligned with the government holidays, according to a statement from the labour and employment ministry.However, owners can also continue work for emergency shipments during the holidays in consultation with the workers, she added.Begum Monnuzan Sufian, state minister for labour and employment, came up with the directives after a tripartite meeting of garment factory owners, union leaders and government officials at Sromo Bhaban in Dhaka.Sufian also said the workers' Eid holiday will be aligned with the government holidays, according to a statement from the labour and employment ministry.However, owners can also continue work for emergency shipments during the holidays in consultation with the workers, she added."
    },{
        id:5,
        type:"entertainment",
        img:"https://i.ibb.co/kMr2SS3/news5.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Shanta Lifestyle's home décor Experience Centre has been launched in Dhaka. The initiative has brought international quality home décor items for patrons in the city through partnerships with award winning global brands such as Moletni & C, Cattelan Italia, Natuzzi and others. The centre aims to present luxurious home ideas for people to experience in reality before buying it for their homes.",
        details:"The most obvious problem with home décor in Bangladesh is how nothing can be found in one place. From a consumer's point of view, they have to go to different areas of the city like Hatirpool or Paltan for tiles and sanitary wares, Kazipara for furniture, etc. to furnish the entire house, or look abroad for high end furniture. With people's perceptions changing over time, they crave beautiful homes with modern, minimalistic setting and are willing to invest heftily to get it.The most obvious problem with home décor in Bangladesh is how nothing can be found in one place. From a consumer's point of view, they have to go to different areas of the city like Hatirpool or Paltan for tiles and sanitary wares, Kazipara for furniture, etc. to furnish the entire house, or look abroad for high end furniture. With people's perceptions changing over time, they crave beautiful homes with modern, minimalistic setting and are willing to invest heftily to get it."
    },{
        id:6,
        type:"sport",
        img:"https://i.ibb.co/hW9tjS2/sp6.jpg",
        time:"07/4/2022  8:10 am",
        heading:"One of Hollywood's most popular stars, Tom Cruise, was born on this day in 1962.The American actor and producer began his career in the 1980s.",
        details:"Forbes ranked the 'Maverick' as one of the most powerful actors in the world, while he is also one of the highest paid actors, with net worth USD 600M.Here is a list of 10 must-watch movies with brilliant performances by Tom Cruise.Yet another hit franchise which has the versatile actor in it. The first Top Gun was released in 1986, featuring Tom Cruise as LT Pete  Mitchell, a US Navy pilot. After 36 years, returned with a sequel this year. The film crossed billions and enthralling the audience across the world.This is one of the most commercially successful movies by Tom Cruise. The 1994 American gothic horror film is directed by Neil Jordan. Based on Anne Rice's 1976 novel of the same name, it stars Tom and Brad Pitt.It focuses on Lestat (Cruise) transforming Louis (Pitt), into a vampire, during 1791. The film chronicles their time together. The narrative is designed by a present-day one on one interview, where Louis tells his story to a San Francisco reporter. "
    },
    {
        id:7,
        type:"business",
        img:"https://i.ibb.co/FbzbqVc/b7.jpg",
        time:"07/4/2022  8:10 am",
        heading:"It's been two years since the closure of 25 jute mills operated by Bangladesh Jute Mills Corporation (BJMC) and the layoff of about 25,000 workers involved with them. This effectively marked the end of our state-run jute sector. How have the workers been faring since then? Although there has been no extensive research of the aftermath of the closure, a report by The Daily Star shows that promises made then are yet to come to fruition, to the detriment of both workers and this once-storied industry.",
        details:"The report, based on a recent visit to at least four mills in Khalishpur, Khulna, highlights how some former workers have been passing their days in hardship, having tried other professions without success. The entire area looks like a  space, and there was no sign of activity with regard to the promised modernisation and reopening of mills under private or public-private arrangements.The report, based on a recent visit to at least four mills in Khalishpur, Khulna, highlights how some former workers have been passing their days in hardship, having tried other professions without success. The entire area looks like a space, and there was no sign of activity with regard to the promised modernisation and reopening of mills under private or public-private arrangements.The report, based on a recent visit to at least four mills in Khalishpur, Khulna, highlights how some former workers have been passing their days in hardship, having tried other professions without success. The entire area looks like a  space, and there was no sign of activity with regard to the promised modernisation and reopening of mills under private or public-private arrangements.The report, based on a recent visit to at least four mills in Khalishpur, Khulna, highlights how some former workers have been passing their days in hardship, having tried other professions without success. The entire area looks like a space, and there was no sign of activity with regard to the promised modernisation and reopening of mills under private or public-private arrangements."
    },{
        id:8,
        type:"sport",
        img:"https://i.ibb.co/Sd6y64N/b8.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Head coach Ian Foster praised England's togetherness after they came from behind to beat Israel and win the European Under-19 Championship.",
        details:"England sailed through their group before coming from behind to beat Italy in the semi-final.Once again they had to dig deep against an impressive Israel team who surprised France in the semi-finals.For the second successive game, England made a slow start and were punished when Gloch produced a clever turn and finish.England got to half-time without conceding a second and turned it around after the break.Once full-back Doyle pounced to make it 1-1 following Jarell Quansah's header across the six-yard box, Ramsey was sent on.He injected some much-needed pace and energy into the play and more chances started to arrive.Chukwuemeka, who has been one of England's standout players at this tournament, struck the post in normal time before England seized control with two goals in the second half of extra time.An outstanding delivery by captain Harvey Vale allowed Chukwuemeka to make it 2-1 from almost point-blank range and Ramsey struck after a superb run by fellow substitute Liam Delap..For the second successive game, England made a slow start and were punished when Gloch produced a clever turn and finish.England got to half-time without conceding a second and turned it around after the break.Once full-back Doyle pounced to make it 1-1 following Jarell Quansah's header across the six-yard box, Ramsey was sent on.He injected some much-needed pace and energy into the play and more chances started to arrive.Chukwuemeka, who has been one of England's standout players at this tournament, struck the post in normal time before England seized control with two goals in the second half of extra time.An outstanding delivery by captain Harvey Vale allowed Chukwuemeka to make it 2-1 from almost point-blank range and Ramsey struck after a superb run by fellow substitute Liam Delap."
    },
    {
        id:9,
        type:"sport",
        img:"https://i.ibb.co/g9XfKhM/sp9.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Ireland name squad for Aus-Pak tri-series",
        details:"Ireland Women 14-member squad for the ti-series involving Australia and Pakistan - to be played at Bready Cricket Club from 16-24 July 2022 - will see the return of a number of high-profile players, who missed out on the South Africa series either due to exams or injuries.Ireland Women's Squad: Laura Delany (C), Ava Canning, Rachel Delaney, Georgina Dempsey, Amy Hunter, Shauna Kavanagh, Arlene Kelly, Gaby Lewis, Sophie MacMahon, Jane Maguire, Cara Murray, Leah Paul, Orla Prendergast, Rebecca Stokell.Ireland Women 14-member squad for the ti-series involving Australia and Pakistan - to be played at Bready Cricket Club from 16-24 July 2022 - will see the return of a number of high-profile players, who missed out on the South Africa series either due to exams or injuries.Ireland Women's Squad: Laura Delany (C), Ava Canning, Rachel Delaney, Georgina Dempsey, Amy Hunter, Shauna Kavanagh, Arlene Kelly, Gaby Lewis, Sophie MacMahon, Jane Maguire, Cara Murray, Leah Paul, Orla Prendergast, Rebecca Stokell."
    },{
        id:10,
        type:"health",
        img:"https://i.ibb.co/cCXx7yX/sp10.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Nursing Home Staffing Shortages: What to Know Before Putting a Family Member in a Facility",
        details:"Charlene Harrington, RN, PhD, FAAN, a professor emeritus in social behavioral sciences at the University of California San Francisco, has studied nursing homes for 40 years. She said the biggest problem is that some of the corporate owners of nursing homes are driven by profits rather than compassion.Many privately owned nursing home corporations routinely release information to the public about how they are allegedly in dire financial straits and cannot afford to hire any more workers, but the truth is they have all kinds of money, especially since 2020, the first year of the pandemic,” Harrington said.A recent studyTrusted Source published by JAMA Health Forum reported that residents in nursing homes acquired by private equity firms were more than 11 percent more likely to have a preventable emergency department visit and nearly 9 percent more likely to experience a preventable hospitalization, when compared to residents of for-profit nursing homes not associated with private equity.Another study from the Americans for Financial Reform Education Fund showed that in New Jersey, private equity-backed nursing homes’ COVID-19 infection rate and death rate were 30 percent and 40 percent above statewide averages.“The entire nursing home industry has long failed residents, families, and workers,” the researchers wrote. “Prior to [the COVID-19 pandemic], the deadly and dehumanizing flaws were often hidden from public view, but the pandemic has exposed the chronic understaffing, poverty wages, and inadequate regulatory oversight and enforcement that has led to a tidal wave of infections and deaths at U.S. nursing homes.”The study concluded, The nation invests too few resources in providing care to our most frail and vulnerable neighbors in nursing homes or in a broader range of caregiving services in the community."
    },{
        id:11,
        type:"health",
        img:"https://i.ibb.co/7jNfT62/he11.png",
        time:"07/4/2022  8:10 am",
        heading:"6 Plant-Based Meat Alternatives for Your Next Summer BBQ",
        details:"Summer brings many opportunities to light a grill and cook up a bounty of juicy meats, corn on the cob, and potatoes for a backyard barbecue.But as more Americans are embracing a plant-based way of eating, traditional BBQ foods are shifting.In fact, a survey from Nielsen found that more than one-third — 39 percent — of Americans say they are actively trying to eat more plant-based foods.“We know that eating more plant-based is good for us and also the environment,” says Vanessa Rissetto, MS, RD, CDN, a registered dietitian in the New York City area. “Tofu, lentils, Impossible Burgers are all great alternatives to meat that are tasty and not just brown rice and steamed vegetables. Also, more plants means more fiber, which is good for your gut health and helps with feeling full.So, if you’re one of those people who are trying to increase the amount of plant-based foods in your diet — or you’re cooking for someone who is — let this list of plant-based foods inspire your next summer BBQ menu."
    },{
        id:12,
        type:"technology",
        img:"https://i.ibb.co/vLVb6mm/te12.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Google is facing action from a coalition of ten European consumer organisations over the company's account sign-up process.",
        details:"A Google account is essential in order to use a number of its products and services.But the coalition alleges the sign-up process steers users towards options that collect more data.Google told the BBC it welcomed the opportunity to engage with consumer advocates on the topic.The company said that consumer trust depended on honesty and transparency and it had.staked our future success on building ever simpler, more accessible controls and giving people clearer choices.And, just as important, doing more with less data.A Google account is essential in order to use a number of its products and services.But the coalition alleges the sign-up process steers users towards options that collect more data.Google told the BBC it welcomed the opportunity to engage with consumer advocates on the topic.The company said that consumer trust depended on honesty and transparency and it had.staked our future success on building ever simpler, more accessible controls and giving people clearer choices.And, just as important, doing more with less data"
    },{
        id:13,
        type:"technology",
        img:"https://i.ibb.co/MNP1RFt/te13.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Many AI systems are trained on large amounts of data copied from the internet.",
        details:"And, on Tuesday, the IPO also announced plans to change copyright law to allow anyone with lawful access - rather than only those conducting non-commercial research, as now - to do this, to promote the use of AI technology, and wider 'data mining' techniques, for the public good.Rights holders will still be able to control and charge for access to their works but no longer charge extra for the ability to mine them.An increasing number of people are using AI tools such as DALL.E 2 to create images resembling a work of human art.And Mr Thaler has recently sued the US Copyright Office over its refusal to recognise a software system as the author of an image, the Register reported.And, on Tuesday, the IPO also announced plans to change copyright law to allow anyone with lawful access - rather than only those conducting non-commercial research, as now - to do this, to promote the use of AI technology, and wider 'data mining' techniques, for the public good.Rights holders will still be able to control and charge for access to their works but no longer charge extra for the ability to mine them.An increasing number of people are using AI tools such as DALL.E 2 to create images resembling a work of human art.And Mr Thaler has recently sued the US Copyright Office over its refusal to recognise a software system as the author of an image, the Register reported."
    },
    {
        id:14,
        type:"technology",
        img:"https://i.ibb.co/crxnZ3P/te14.png",
        time:"07/4/2022  8:10 am",
        heading:"Apple co-founder Steve Jobs will be posthumously awarded the Presidential Medal of Freedom, the White House said Friday, recognizing his accomplishments as the head of Apple and Pixar, as well as his leading role at the Walt Disney Company.",
        details:"His vision, imagination and creativity led to inventions that have, and continue to, change the way the world communicates, as well as transforming the computer, music, film and wireless industries the White House said in a statemen President Joe Bidens recognition for Jobs marks the latest of accolades the former Apple CEO has received since he died of cancer in 2011. He received an Edison Lifetime Achievement Award in 2012, honoring the successful development and launch of game-changing new products and services as well as his lasting contribution to innovation. In 2013, Jobs received a Disney Legends Award for his contribution to the Disney legacy as Pixar CEO and later a board member.The announcement came the same week that marked the 15th anniversary of the launch of the original iPhone.The Presidential Medal of Freedom is the highest civilian honor in the US. Basketball star Michael Jordan received the honor in 2016, as did entertainment Oprah Winfrey in 2015 and feminist activist Gloria Steinem in 2013.Others have received the award posthumously, including civil rights giant the Rev. Martin Luther King Jr. in 1977 and music legend Elvis Presley and baseball great Babe Ruth, both in 2018.This year presentation ceremony is set for July 7 at the White House. The 17 recipients will also include two Olympic gold medal winners, gymnastics icon Simone Biles and soccer star Megan Rapinoe, as well as former US Rep. and gun-safety advocate Gabrielle Giffords and actor Denzel Washington. "
    },{
        id:15,
        type:"entartainment",
        img:"https://i.ibb.co/DVbVwfY/en15.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Dhanush is ‘super kicked’ about Arun Matheswaran’s Captain Miller, shares teaser: ‘This is going to be exciting’",
        details:"Dhanush on Saturday shared a teaser in which he announced the title of his next. The actor is collaborating with director Arun Matheswaran for Captain Miller. Going by the teaser, the film looks like a historical drama. Sharing the video on his Twitter account, Dhanush promised that Captain Miller is “going to be so exciting.” He also expressed that he is “super kicked” to be working with Arun and GV Prakash, who is composing music for the film.Trade analyst Sreedhar Pillai shared some more details about the film. He informed that Captain Miller will be a period action-adventure drama set in Madras Presidency period of 1930’s & 40’s. He also informed the fans that Dhanush will don three different looks in the film.Dhanush had announced the project in December last year. He wrote in a tweet that he is “fortunate” to be working in Arun’s directorial. In response to the tweet, Arun had tweeted, “Thank you so much for the trust @dhanushkraja. I am humbled and truly honoured for your kind words. I am the fortunate one here. Looking forward to this big journey.”"
    },
    {
        id:16,
        type:"entartainment",
        img:"https://i.ibb.co/LJg9zgw/en16.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Rohit Shetty's Khatron Ke Khiladi 12 saw its launch on July 2.",
        details:"Rohit Shetty is all set with the new ‘blockbuster’ season of Khatron Ke Khiladi 12. The filmmaker says that it’s the love for the show that keeps bringing him back. “It’s one of a kind, and you will not see a similar show on any other platform or channel. Also, my love for action attracts me towards hosting KKK. And most importantly, the love that I get from the audience. It just makes everything more special,” Rohit told indianexpress.com.He added that he takes back multiple experiences every year, and also gets to learn so much from each of the contestants. “We are usually working in the office or making films. Coming here (Cape Town) to shoot for Khatron brings the much-needed break. Also, I work with the same team so it’s like a big reunion with my other family. It’s not an easy show at all, but these challenges make it more special. Getting to see these contestants toil hard, and fight their fears gives you the push in life too.”"
    },
    {
        id:17,
        type:"bangladesh",
        img:"https://i.ibb.co/f0J2zXH/bd17.jpg",
        time:"07/4/2022  8:10 am",
        heading:"Was it at all surprising, then, that there would be mayhem on that day? That the crowd would disregard civility and break the law? Photo: Courtesy/NewsBangla",
        details:"Despite all of these being illegal and dangerously unsafe, they broke fences, they stopped and got off everywhere on the bridge and made TikTok videos doing I-don't-know-what-that-is-even poses. Some even performed namaz. Overspeeding killed two; some urinated on the bridge. Then there was a guy who, after a good beating from the police, said with a broad smile that if he couldn't get onto the Padma Bridge, his heart would've shattered (the original Bangla version Koilja faitta moirai jaitam is way funnier). And then there was a 30-something woman saying, I always saw this bridge on Facebook and TV and everyone in the village was coming here. So, I got into a pickup truck too.Despite all of these being illegal and dangerously unsafe, they broke fences, they stopped and got off everywhere on the bridge and made TikTok videos doing I-don't-know-what-that-is-even poses. Some even performed namaz. Overspeeding killed two; some urinated on the bridge. Then there was a guy who, after a good beating from the police, said with a broad smile that if he couldn't get onto the Padma Bridge, his heart would've shattered (the original Bangla version Koilja faitta moirai jaitam is way funnier). And then there was a 30-something woman saying, I always saw this bridge on Facebook and TV and everyone in the village was coming here. So, I got into a pickup truck too."
    },
    {
        id:18,
        type:"bangladesh",
        img:"https://i.ibb.co/k24CgyV/bd18.jpg",
        time:"07/4/2022  8:10 am",
        heading:"University of dhaka: The Trillion Dollar Opportunity Cost",
        details:"People usually tend to believe that there were universities in ancient India or Arabia. Some claim that the crusaders brought the idea of the university from the Middle East to Europe. In my view, these are total misconceptions. Plato and Aristotle had each found their academies in Athens. There were famous educational institutions in Taxila and Nalanda in India and huge madrasas in Arabia. These institutions may have been similar to or even bigger than the universities of today, but none was in fact a university.University is a particular type of institution that was created in the latter half of the Middle-ages 1000-1500 in Europe due to specific socio-politico-economic conditions that existed nowhere in the world at that time or earlier. A new class of bourgeois started to form during that period of time and they tried to cocoon themselves by forming guilds which were called universities in the then Latin. There were universities of barbers, potters, smiths, students, and teachers.For all latest news, follow The Daily Star's Google News channel.Later, the meaning of the word university got narrowed to denote 'organization of students' in Italy and 'organization of teachers' in Paris. During the 11-12th century, there were two different models of university, the Bologna model and the Paris model, of which only the latter survived. In the Paris model, students were admitted to the affiliated colleges. The college administration constituted of the Provost, the Dean, the Proctor, the House tutors, and of course, the teachers. Colleges were responsible for education whereas the university's responsibility was to organize the examinations and confer degrees on the successful students."
    },
    {
        id:19,
        type:"bangladesh",
        img:"https://i.ibb.co/F0GjfGD/b3.jpg",
        time:"07/4/2022  8:10 am",
        heading:"A look into post-pandemic cattle markets in city",
        details:"However, the statistics of the Department of Livestock is showing a different picture. According to them, 1 crore 21 lakh 24 thousand sacrificial animals were reared this year against the demand of 97.75 lakh across the country.About 9,093,242 cattle were sacrificed across the country last year, as per data from the Ministry of Fisheries and Livestock.Last year's loss, high price of cattle feed and cattle in local markets during the beginning of the seasons were the main causes of reduced production, said Md Ashraful Alam, a trader from Chuadanga.However, the statistics of the Department of Livestock is showing a different picture. According to them, 1 crore 21 lakh 24 thousand sacrificial animals were reared this year against the demand of 97.75 lakh across the country.About 9,093,242 cattle were sacrificed across the country last year, as per data from the Ministry of Fisheries and Livestock.Last year's loss, high price of cattle feed and cattle in local markets during the beginning of the seasons were the main causes of reduced production, said Md Ashraful Alam, a trader from Chuadanga."
    }
]